packages:
  - '.'
  - 'cli'
  - 'docs'

overrides:
  sharp: 0.34.5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

patchedDependencies:
  '@jsr/deno__doc@0.189.1': patches/@jsr__deno__doc@0.189.1.patch

packageExtensions:
  '@nuxt/scripts':
    dependencies:
      estree-walker: '^3.0.3'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3@12.5.0
  - sharp@0.34.5
  - simple-git-hooks@2.13.1

ignoreWorkspaceRootCheck: true
